; PlatformIO — MediBox Firmware
; IDE recomendada: VS Code + extensão PlatformIO

[env:esp32dev]
platform    = espressif32
board       = esp32dev
framework   = arduino

; Velocidade do monitor serial
monitor_speed = 115200

; Bibliotecas necessárias
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  madhephaestus/ESP32Servo @ ^3.0.5

; Flags de build
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -std=gnu++17

; Nível de otimização
build_type = release
